var ActionTypes = {
    "SKUS": {
        "FETCH_ALL_STARTED": "SKUS.FETCH_ALL_STARTED",
        "FETCH_ALL_SUCCESS": "SKUS.FETCH_ALL_SUCCESS",
        "FETCH_ALL_FAILURE": "SKUS.FETCH_ALL_FAILURE",

        "GET_DETAILS_STARTED": "GET_DETAILS_STARTED",
        "GET_DETAILS_SUCCESS": "GET_DETAILS_SUCCESS",
        "GET_DETAILS_FAILURE": "GET_DETAILS_FAILURE",

        "SELECT": "SKUS.SELECT"
    }

};

module.exports = ActionTypes;