var ActionTypes = {
    "PRODUCTS": {
        "FETCH_ALL_STARTED": "PRODUCTS.FETCH_ALL_STARTED",
        "FETCH_ALL_SUCCESS": "PRODUCTS.FETCH_ALL_SUCCESS",
        "FETCH_ALL_FAILURE": "PRODUCTS.FETCH_ALL_FAILURE",

        "GET_DETAILS_STARTED": "PRODUCTS.GET_DETAILS_STARTED",
        "GET_DETAILS_SUCCESS": "PRODUCTS.GET_DETAILS_SUCCESS",
        "GET_DETAILS_FAILURE": "PRODUCTS.GET_DETAILS_FAILURE",

        "SELECT": "PRODUCTS.SELECT"
    }

};

module.exports = ActionTypes;